### ISSUE TITLE
superagent: Enable experimental feature http2

### ISSUE THREAD

**Issue by Binit-Dhakal** [ad-m/anticaptcha-async#1]
I am new to javascript and excuse me if this is some simple question. I copied your code in the readme.md and with my anti-captcha-key, it shows this weird error "superagent: Enable experimental feature http2" and exit out. 
After googling I came to this issue in superagent "https://github.com/visionmedia/superagent/issues/1430" but the thread reads like it is just a warning and it might be thrown because of the 403  error by the server. 
Can you please explain what this is and is this really the issue/bug of the library?

Thank you

**Comment by ad-m** [comment]
@Binit-Dhakal I believe this warning is not related to your issue at all. 

Could you provide full content of file? I suppose that you miss usage of defined function "process" eg. by adding line like:
```javascript
process()
.then(() => console.log("Success"))
.catch(err => console.error("Failure:", err));
```
